[project]
name = "AreYouCommentBanned"
version = "1.0"
description = "Verify if you are comment banned in Geometry Dash"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.17.0",
    "requests>=2.32.5",
]
